import type { BestiaryPreset } from "./types";
import { GENERATED_DSA5_PRESETS, GENERATED_LEGACY_PRESETS, ZBA_ENRICHMENTS } from "./generated-bestiary-data";

const a = (name: string, type: "AT" | "FK", value: number, damage: string, parry?: number, range?: string) => ({ name, type, value, damage, ...(parry === undefined ? {} : { parry }), ...(range ? { range } : {}) });

export const HUMAN_OPPONENT_PRESETS: BestiaryPreset[] = [
  { id:"mensch-streuner", name:"Streuner", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Profane.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Unterwelt", size:"mittel", initiative:12, lp:25, defense:6, rs:0, sk:0, zk:0, gs:8, actions:1, attacks:[a("Knüppel","AT",10,"1W6+2",6),a("Messer","AT",9,"1W6+1",5)], equipment:"Knüppel, Messer, zerschlissene Kleidung, 1W6 Heller", notes:"Weicht einem aussichtslosen Kampf meist aus; kennt Gassen und Verstecke." },
  { id:"mensch-stadtgardist", name:"Stadtgardist", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Kämpfer.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Ordnungsmacht", size:"mittel", initiative:13, lp:30, defense:8, rs:2, sk:1, zk:1, gs:8, actions:1, attacks:[a("Hellebarde","AT",13,"1W6+5",8),a("Kurzschwert","AT",12,"1W6+2",8)], equipment:"Hellebarde, Kurzschwert, Tuchrüstung, Signalpfeife, Handschellen", notes:"Handelt in Zweiergruppen; fordert Verdächtige zunächst zur Aufgabe auf." },
  { id:"mensch-soldat", name:"Soldat", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Kämpfer.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Militär", size:"mittel", initiative:13, lp:32, defense:8, rs:3, sk:1, zk:2, gs:8, actions:1, attacks:[a("Speer","AT",14,"1W6+4",8),a("Kurzschwert","AT",12,"1W6+2",8)], equipment:"Speer, Kurzschwert, leichte Rüstung, Feldflasche, Marschgepäck", notes:"Hält die Formation und unterstützt Verbündete; gehorcht klaren Befehlen." },
  { id:"mensch-soeldner", name:"Söldner", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Kämpfer.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Bewaffnete", size:"mittel", initiative:14, lp:34, defense:9, rs:4, sk:1, zk:2, gs:8, actions:1, attacks:[a("Langschwert","AT",14,"1W6+4",9),a("Dolch","AT",12,"1W6+1",7)], equipment:"Langschwert, Dolch, Kettenhemd, Proviant für drei Tage", notes:"Kämpft professionell, zieht sich aber zurück, wenn Sold oder Erfolgsaussicht fehlen." },
  { id:"mensch-pirat", name:"Pirat", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Kämpfer.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Seefahrer", size:"mittel", initiative:14, lp:30, defense:8, rs:1, sk:0, zk:1, gs:8, actions:1, attacks:[a("Entermesser","AT",13,"1W6+3",8),a("Wurfmesser","FK",11,"1W6+1",undefined,"2/10/15")], equipment:"Entermesser, zwei Wurfmesser, Lederjacke, Enterhaken und Seil", notes:"Versucht Gegner einzukreisen oder über Bord zu drängen; tritt selten allein auf." },
  { id:"mensch-strassenraeuber", name:"Straßenräuber", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Profane.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Unterwelt", size:"mittel", initiative:13, lp:27, defense:7, rs:1, sk:0, zk:0, gs:8, actions:1, attacks:[a("Knüppel","AT",12,"1W6+2",7),a("Dolch","AT",11,"1W6+1",6)], equipment:"Knüppel, Dolch, dicke Lederkleidung, dunkler Umhang", notes:"Greift bevorzugt überrascht und in Überzahl an; flieht frühzeitig." },
  { id:"mensch-wegelagerer", name:"Wegelagerer", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Profane.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Räuberbande", size:"mittel", initiative:13, lp:30, defense:8, rs:2, sk:0, zk:1, gs:8, actions:1, attacks:[a("Säbel","AT",13,"1W6+3",8),a("Kurzbogen","FK",12,"1W6+4",undefined,"10/50/80")], equipment:"Säbel, Kurzbogen mit 12 Pfeilen, Tuchrüstung, Halstuch", notes:"Eröffnet den Kampf aus der Deckung und verlangt meist zuerst Wertsachen." },
  { id:"mensch-schlaeger", name:"Schläger", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Profane.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Unterwelt", size:"mittel", initiative:12, lp:32, defense:7, rs:1, sk:0, zk:2, gs:8, actions:1, attacks:[a("Schlagring","AT",13,"1W6+2",7),a("Knüppel","AT",12,"1W6+2",7)], equipment:"Schlagring, Knüppel, verstärkte Lederkleidung", notes:"Bedroht und bedrängt einzelne Ziele; versucht Gegner niederzuringen." },
  { id:"mensch-bogenschuetze", name:"Bogenschütze", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Kämpfer.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Fernkämpfer", size:"mittel", initiative:14, lp:27, defense:7, rs:1, sk:0, zk:0, gs:8, actions:1, attacks:[a("Kurzbogen","FK",14,"1W6+4",undefined,"10/50/80"),a("Kurzschwert","AT",10,"1W6+2",7)], equipment:"Kurzbogen mit 20 Pfeilen, Kurzschwert, Lederkleidung", notes:"Sucht Deckung und Abstand; wechselt erst im Nahkampf zum Kurzschwert." },
  { id:"mensch-leibwaechter", name:"Leibwächter", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Kämpfer.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Bewaffnete", size:"mittel", initiative:14, lp:36, defense:10, rs:4, sk:1, zk:2, gs:8, actions:1, attacks:[a("Langschwert","AT",15,"1W6+4",10),a("Schildstoß","AT",12,"1W6+1",9)], equipment:"Langschwert, Holzschild, Kettenhemd, verstärkte Handschuhe", notes:"Bleibt beim Schützling, blockiert Wege und kämpft defensiv." },
  { id:"mensch-kultist", name:"Kultist", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Profane.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Verschwörer", size:"mittel", initiative:12, lp:26, defense:7, rs:1, sk:1, zk:0, gs:8, actions:1, attacks:[a("Dolch","AT",11,"1W6+1",6),a("Kampfstab","AT",10,"1W6+2",7)], equipment:"Dolch, Kampfstab, Robe, Kultzeichen, Räucherwerk", notes:"Fanatisch und schwer einzuschüchtern; schützt Anführer oder Ritualort." },
  { id:"mensch-veteran", name:"Veteran", category:"Menschengegner", rulesEdition:"DSA5", playable:true, sourceUrl:"https://dsa.ulisses-regelwiki.de/Pro_Kämpfer.html", sourceBook:"Vereinfachtes DSA-5-Spielleiterprofil", group:"Militär", size:"mittel", initiative:14, lp:38, defense:10, rs:4, sk:2, zk:2, gs:8, actions:1, attacks:[a("Langschwert","AT",16,"1W6+4",10),a("Wurfspeer","FK",12,"1W6+4",undefined,"5/25/40")], equipment:"Langschwert, zwei Wurfspeere, Kettenhemd, kleiner Schild", notes:"Erkennt gefährliche Ziele, nutzt Gelände und hält auch unter Druck die Stellung." },
];

const CURATED_PRESETS: Array<Omit<BestiaryPreset, "rulesEdition" | "playable">> = [
  { id:"waldwolf", name:"Waldwolf", category:"Tiere", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Waldwolf.html", sourceBook:"DSA Regelwiki", size:"mittel", initiative:14, lp:18, defense:7, rs:0, sk:-1, zk:0, gs:12, actions:1, attacks:[a("Biss","AT",13,"1W6+3")], notes:"Dunkelsicht I; hervorragender Geruch; Verbeißen." },
  { id:"wildschwein", name:"Wildschwein", category:"Tiere", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Wildschwein.html", sourceBook:"Aventurischer Almanach S. 170", size:"mittel", initiative:11, lp:35, defense:5, rs:0, sk:-2, zk:5, gs:10, actions:1, attacks:[a("Biss und Stoß","AT",15,"1W6+4"),a("Rammen","AT",13,"1W6+3")], notes:"Herausragender Geruch; Zu Fall bringen mit Rammen." },
  { id:"tiger", name:"Tiger", category:"Tiere", sourceUrl:"https://dsa.ulisses-regelwiki.de/Tiger.html", sourceBook:"Das Dornenreich S. 92", size:"groß", initiative:16, lp:50, defense:8, rs:0, sk:-2, zk:0, gs:14, actions:2, attacks:[a("Biss","AT",15,"2W6+3"),a("Pranke","AT",15,"1W6+4")], notes:"Maximal ein Biss pro Runde; Anspringen und Verbeißen." },
  { id:"riesenratte", name:"Riesenratte", category:"Tiere", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Tiere/ratten-arten/riesenratte.html", sourceBook:"Verborgen in der Tiefe S. 124", size:"klein", initiative:12, lp:5, defense:7, rs:0, sk:1, zk:2, gs:6, actions:1, attacks:[a("Biss","AT",8,"1W6 (+Krankheit)")], notes:"Dunkelsicht II; Angst vor Feuer II; kann Krankheiten übertragen." },
  { id:"gruftassel", name:"Gruftassel", category:"Tiere", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Gruftassel.html", sourceBook:"DSA Regelwiki", size:"groß", initiative:6, lp:40, defense:7, rs:4, sk:-4, zk:0, gs:4, actions:1, attacks:[a("Zangen","AT",10,"1W6+4")], notes:"Dunkelsicht II; stark gepanzert." },
  { id:"goblin", name:"Goblin", category:"Kulturschaffende", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Kulturschaffende/goblin.html", sourceBook:"Aventurischer Almanach S. 151", size:"mittel", initiative:13, lp:24, defense:8, rs:0, sk:-1, zk:0, gs:8, actions:1, attacks:[a("Waffenlos","AT",11,"1W6+1",6),a("Kurzbogen","FK",9,"1W6+4",undefined,"10/50/80")], notes:"Dunkelsicht I; Kälteresistenz; Finte I." },
  { id:"oger", name:"Oger", category:"Kulturschaffende", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Kulturschaffende/oger.html", sourceBook:"DSA Regelwiki", size:"groß", initiative:13, lp:60, ae:30, defense:6, rs:0, sk:-1, zk:5, gs:8, actions:1, attacks:[a("Waffenlos","AT",12,"1W6+8",8),a("Oger-Axt","AT",9,"2W6+9",8),a("Großer Stein","FK",10,"2W6",undefined,"4/20/32")], notes:"Sehr kräftiger Kulturschaffender; mehrere Waffenoptionen." },
  { id:"hoehlenoger", name:"Höhlenoger", category:"Kulturschaffende", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Kulturschaffende/hoehlenoger.html", sourceBook:"Verborgen in der Tiefe S. 113", size:"mittel", initiative:14, lp:60, defense:6, rs:2, sk:0, zk:5, gs:8, actions:1, attacks:[a("Waffenlos","AT",10,"1W6+8",8),a("Keule","AT",9,"1W6+10",7),a("Großer Stein","FK",10,"2W6",undefined,"4/20/32")], notes:"Blindkampf I–II; Mächtiger Schlag; flieht nicht." },
  { id:"skelett", name:"Skelett", category:"Untote", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Skelett.html", sourceBook:"DSA Regelwiki", size:"mittel", initiative:8, lp:14, defense:6, rs:0, sk:-1, zk:-1, gs:8, actions:1, attacks:[a("Waffenlos","AT",10,"1W6",4),a("Langschwert","AT",11,"1W6+4",6),a("Kurzbogen","FK",10,"1W6+4",undefined,"10/50/80")], notes:"Untoten-Regeln; Rüstung kann nachträglich angepasst werden." },
  { id:"zombie", name:"Zombie", category:"Untote", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Zombie.html", sourceBook:"Aventurisches Bestiarium S. 87", size:"mittel", initiative:7, lp:16, defense:1, rs:0, sk:0, zk:0, gs:4, actions:1, attacks:[a("Waffenlos","AT",8,"1W6 (+Krankheit)"),a("Biss","AT",8,"1W6+2 (+Krankheit)")], notes:"Untoten-Regeln; 2 SP je KR in direktem Sonnenlicht; Meute." },
  { id:"goblinskelett", name:"Goblinskelett", category:"Untote", sourceUrl:"https://dsa.ulisses-regelwiki.de/BEST_Goblinskelett.html", sourceBook:"DSA Regelwiki", size:"mittel", initiative:11, lp:11, defense:6, rs:0, sk:1, zk:2, gs:10, actions:1, attacks:[a("Waffenlos","AT",11,"1W6",5),a("Säbel","AT",10,"1W6+3",4),a("Kurzbogen","FK",12,"1W6+4",undefined,"10/50/80")], notes:"Untoten-Regeln; lichtempfindlich." },
  { id:"zwergenskelett", name:"Zwergenskelett", category:"Untote", sourceUrl:"https://dsa.ulisses-regelwiki.de/BEST_Zwergenskelett.html", sourceBook:"DSA Regelwiki", size:"mittel", initiative:7, lp:17, defense:5, rs:1, sk:0, zk:1, gs:4, actions:1, attacks:[a("Streitaxt","AT",10,"1W6+5",5),a("Zwergenschlägel","AT",10,"1W6+8",5),a("Leichte Armbrust","FK",10,"1W6+7",undefined,"10/50/80")], notes:"Untoten-Regeln; extrem lichtempfindlich; Meute." },
  { id:"elfenskelett", name:"Elfenskelett", category:"Untote", sourceUrl:"https://dsa.ulisses-regelwiki.de/BEST_Elfenskelett.html", sourceBook:"DSA Regelwiki", size:"mittel", initiative:10, lp:11, defense:6, rs:0, sk:2, zk:1, gs:9, actions:1, attacks:[a("Wolfsmesser","AT",11,"1W6+3",5),a("Elfenbogen","FK",11,"1W6+5",undefined,"50/100/200")], notes:"Untoten-Regeln; lichtempfindlich." },
  { id:"oboraddon", name:"Oboraddon", category:"Dämonen", sourceUrl:"https://dsa.ulisses-regelwiki.de/Best_Oboraddon.html", sourceBook:"Aventurisches Pandämonium S. 71", size:"variabel", initiative:17, lp:100, ae:80, defense:3, rs:5, sk:5, zk:5, gs:4, actions:2, attacks:[a("Klaue","AT",15,"1W6+7",5)], notes:"Sechsgehörnter Dämon; Meisteruntoter; Werte des Gastkörpers können hinzukommen." }
];

const normalize = (value: string): string => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("de").replace(/[^a-z0-9]+/g, "");

const enrichedCurated: BestiaryPreset[] = CURATED_PRESETS.map((preset) => ({
  ...preset,
  rulesEdition: "DSA5",
  playable: true,
  ...(ZBA_ENRICHMENTS[normalize(preset.name)] || {}),
}));

export const BESTIARY_PRESETS: BestiaryPreset[] = [
  ...HUMAN_OPPONENT_PRESETS,
  ...enrichedCurated,
  ...GENERATED_DSA5_PRESETS,
  ...GENERATED_LEGACY_PRESETS,
];

export const BESTIARY_CATEGORIES = [...new Set(BESTIARY_PRESETS.map((preset) => preset.category))].sort((a,b) => a.localeCompare(b,"de"));
export const BESTIARY_COUNTS = {
  total: BESTIARY_PRESETS.length,
  dsa5: BESTIARY_PRESETS.filter((preset) => preset.rulesEdition === "DSA5").length,
  legacy: BESTIARY_PRESETS.filter((preset) => preset.rulesEdition === "DSA4.1").length,
  legacyPlayable: BESTIARY_PRESETS.filter((preset) => preset.rulesEdition === "DSA4.1" && preset.playable).length,
};
